### ISSUE TITLE
Flaky Tests

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/ruby-docs-samples#108]
**Possible reason**
A resource race-condition, running more than one instance of _ruby-docs-samples_ tests will cause an error related to a resource being in use. 

**Storage and Datastore**
[Storage-Example-1](https://circleci.com/gh/GoogleCloudPlatform/ruby-docs-samples/222?utm_campaign=vcs&integration-link&utm_medium=referral&utm_source=github-build-link)
[Storage-Example-2](https://circleci.com/gh/GoogleCloudPlatform/ruby-docs-samples/263)
[Datastore-and-Storage-Example](https://circleci.com/gh/GoogleCloudPlatform/ruby-docs-samples/227?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**BigQuery**
[Example-1](https://circleci.com/gh/GoogleCloudPlatform/ruby-docs-samples/219?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
[Example-2](https://circleci.com/gh/GoogleCloudPlatform/ruby-docs-samples/224#tests/containers/0)
[Example-3](https://circleci.com/gh/GoogleCloudPlatform/ruby-docs-samples/209?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by remi** [comment]
Please update title and description with details of particular tests that break

The links do not point to CicleCI build output, they are for pull requests

**Comment by frankyn** [comment]
I cherry picked some examples and updated the description. Does this help?

**Comment by frankyn** [comment]
Fixed in #211
