### ISSUE TITLE
Move away from poltergeist in capybara tests

### ISSUE THREAD

**Issue by SandeepTuniki** [GoogleCloudPlatform/ruby-docs-samples#1096]
Issue noticed while fixing #853.

We're using [poltergeist](https://github.com/teampoltergeist/poltergeist) in many samples' acceptance tests. The gem is [unmaintained](https://github.com/teampoltergeist/poltergeist/issues/936) since 2020 atleast, so we need to move away from it.

Some possible alternatives are mentioned in Capybara's home page - https://github.com/teamcapybara/capybara#drivers

Also, [some of the tests](https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/b52cdd3641463860422d494cb1407910ed288633/appengine/metadata_server/spec/metadata_server_spec.rb#L32) don't need to rely on headless browser, since they don't have any UI interactions. We can replace them with simple HTTP client calls

**Comment by shivgautam** [comment]
This is completed.
