### ISSUE TITLE
Create samples for storageinsights

### ISSUE THREAD

**Issue by JesseLovelace** [GoogleCloudPlatform/ruby-docs-samples#1106]
Please create the following samples for the Storage Insights API, using [this](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/storageinsights/src/main/java/com/google/cloud/storage/storageinsights/samples) as a reference 

storageinsights_create_inventory_report_config
storageinsights_delete_inventory_report_config
storageinsights_edit_inventory_report_config
storageinsights_get_inventory_report_names
storageinsights_list_inventory_report_configs

**Comment by meredithslota** [comment]
Samples are generated for Storage Insights are here: https://github.com/googleapis/google-cloud-ruby/tree/main/google-cloud-storage_insights-v1/snippets/storage_insights I'm curious if there's a gap that needs to be addressed or if the generated snippets are sufficient? Can we improve the generated snippets first?

**Comment by iennae** [comment]
hey @JesseLovelace I'm going to go ahead and close this issue due to its age. If there are additional samples needed, please do reopen with more details.
