### ISSUE TITLE
Update samples to instantiate clients via Google::Cloud::[Product].new

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/ruby-docs-samples#112]
Currently, samples instantiate product service clients using this syntax to be consistent with the [Official google-cloud-ruby documentation](https://googlecloudplatform.github.io/google-cloud-ruby/#/)

```ruby
require "google/cloud"

gcloud = Google::Cloud.new
translate = gcloud.translate
```

Samples should be updated to use the following syntax instead:

```ruby
translate = Google::Cloud::Translate.new
```

**Comment by frankyn** [comment]
This has been completed.
