### ISSUE TITLE
Add BigQuery sample : run all INSERT statements in a file

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/ruby-docs-samples#117]
See Python example: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/dml/insert_sql.py

Documentation: https://cloud.google.com/bigquery/docs/loading-data-sql-dml#loading_data_using_sql_dml

**Comment by tswast** [comment]
We've removed those samples from the BigQuery documentation. Insert statements with DML have more limitations and costs than using a load job, so the page containing these sample needs a rewrite.
