### ISSUE TITLE
security in openapi.yaml now needs to be under the method

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/ruby-docs-samples#139]
The following in [`openapi.yaml`](https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/appengine/endpoints/openapi.yaml#L110) does not have effect anymore:

```yaml
# This section requires all requests to any path to require an API key.
security:
- api_key: []
```

Instead it needs to be moved under the method (like in the [python sample](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/endpoints/getting-started/openapi.yaml#L35)):

```yaml
paths:
  "/echo":
    post:
      description: "Echo back a given message."
      operationId: "echo"
      produces:
      - "application/json"
      responses:
        200:
          description: "Echo"
          schema:
            $ref: "#/definitions/echoMessage"
      parameters:
      - description: "Message to echo"
        in: body
        name: message
        required: true
        schema:
          $ref: "#/definitions/echoMessage"
      security:
      - api_key: []
```

see [endpoints docs](https://cloud.google.com/endpoints/docs/restricting-api-access-with-api-keys-openapi#restricting_access_to_specific_api_methods) for more info.

**Comment by p-buse** [comment]
https://github.com/GoogleCloudPlatform/ruby-docs-samples/commit/a5006e809651b5fc86d99adb757725e3ed521fd2
