### ISSUE TITLE
datastore_api.rb:28:in `require': cannot load such file -- google/gax (LoadError)

### ISSUE THREAD

**Issue by palladius** [GoogleCloudPlatform/ruby-docs-samples#152]
I'm trying to get the Appengine Datastore sample to work.

$ export GOOGLE_CLOUD_PROJECT=myproject
$  bundle
$  bundle exec ruby ./app.rb 
/var/lib/gems/2.3.0/gems/google-cloud-datastore-0.21.0/lib/google/cloud/datastore/v1/datastore_api.rb:28:in `require': cannot load such file -- google/gax (LoadError)
	from /var/lib/gems/2.3.0/gems/google-cloud-datastore-0.21.0/lib/google/cloud/datastore/v1/datastore_api.rb:28:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/google-cloud-datastore-0.21.0/lib/google/cloud/datastore/v1.rb:16:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-datastore-0.21.0/lib/google/cloud/datastore/v1.rb:16:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/google-cloud-datastore-0.21.0/lib/google/cloud/datastore/service.rb:19:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-datastore-0.21.0/lib/google/cloud/datastore/service.rb:19:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/google-cloud-datastore-0.21.0/lib/google/cloud/datastore/dataset.rb:19:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-datastore-0.21.0/lib/google/cloud/datastore/dataset.rb:19:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/google-cloud-datastore-0.21.0/lib/google/cloud/datastore.rb:18:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-datastore-0.21.0/lib/google/cloud/datastore.rb:18:in `<top (required)>'
	from ./app.rb:18:in `require'
	from ./app.rb:18:in `<main>'

$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.5.0)
      public_suffix (~> 2.0, >= 2.0.2)
    diff-lcs (1.2.5)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    google-cloud-core (0.21.0)
    google-cloud-datastore (0.21.0)
      google-cloud-core (~> 0.21.0)
      google-gax (~> 0.6.0)
      google-protobuf (~> 3.0)
      googleapis-common-protos (~> 1.3)
      grpc (~> 1.0)
    google-gax (0.6.0)
      googleapis-common-protos (~> 1.3.1)
      googleauth (~> 0.5.1)
      grpc (~> 1.0)
      rly (~> 0.2.3)
    google-protobuf (3.0.2)
    googleapis-common-protos (1.3.4)
      google-protobuf (~> 3.0)
      grpc (~> 1.0)
    googleauth (0.5.1)
      faraday (~> 0.9)
      jwt (~> 1.4)
      logging (~> 2.0)
      memoist (~> 0.12)
      multi_json (~> 1.11)
      os (~> 0.9)
      signet (~> 0.7)
    grpc (1.0.1)
      google-protobuf (~> 3.0.2)
      googleauth (~> 0.5.1)
    jwt (1.5.6)
    little-plugger (1.1.4)
    logging (2.1.0)
      little-plugger (~> 1.1)
      multi_json (~> 1.10)
    memoist (0.15.0)
    multi_json (1.12.1)
    multipart-post (2.0.0)
    os (0.9.6)
    public_suffix (2.0.4)
    rack (1.6.4)
    rack-protection (1.5.3)
      rack
    rly (0.2.3)
    rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-core (3.5.4)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)
    signet (0.7.3)
      addressable (~> 2.3)
      faraday (~> 0.9)
      jwt (~> 1.5)
      multi_json (~> 1.10)
    sinatra (1.4.7)
      rack (~> 1.5)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    tilt (2.0.5)

PLATFORMS
  ruby

DEPENDENCIES
  google-cloud-datastore
  rspec
  sinatra

BUNDLED WITH
   1.13.4

**Comment by frankyn** [comment]
Hi @palladius,

Thanks for filing this issue! The google-cloud gem has had updates since we last updated this sample. Could you do a `bundle update` and let us know the result? I believe this is related to gem versions. 

Thank you.

**Comment by frankyn** [comment]
Closing with no response. Please reopen if you are still experiencing this issue.
