### ISSUE TITLE
Monitoring Samples need to be written

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/ruby-docs-samples#359]
Samples need to be written and put in the `/monitoring` directory with README and tests:
- [ ] [monitoring_quickstart](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/061b898007acc2be55b3f1e1bbdec470c4423b03/monitoring/api/v3/cloud-client/quickstart.py#L18-L38) [doc](https://cloud.google.com/monitoring/docs/reference/libraries)
- [ ] [monitoring_create_metric](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/56a6b16fa1a8fa70df7b5018b12de815e1b504dd/monitoring/api/v3/cloud-client/snippets.py#L30-L40) [doc](https://cloud.google.com/monitoring/custom-metrics/creating-metrics)
- [ ] [monitoring_delete_metric](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/56a6b16fa1a8fa70df7b5018b12de815e1b504dd/monitoring/api/v3/cloud-client/snippets.py#L46-L48) [doc](https://cloud.google.com/monitoring/custom-metrics/creating-metrics)
- [ ] [monitoring_write_timeseries](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/56a6b16fa1a8fa70df7b5018b12de815e1b504dd/monitoring/api/v3/cloud-client/snippets.py#L54-L68) [doc](https://cloud.google.com/monitoring/custom-metrics/creating-metrics)
- [ ] [monitoring_read_timeseries_simple](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/56a6b16fa1a8fa70df7b5018b12de815e1b504dd/monitoring/api/v3/cloud-client/snippets.py#L74-L89) [doc](https://cloud.google.com/monitoring/custom-metrics/reading-metrics)
- [ ] [monitoring_read_timeseries_fields](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/56a6b16fa1a8fa70df7b5018b12de815e1b504dd/monitoring/api/v3/cloud-client/snippets.py#L95-L110) [doc](https://cloud.google.com/monitoring/custom-metrics/reading-metrics)
- [ ] [monitoring_read_timeseries_align](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/56a6b16fa1a8fa70df7b5018b12de815e1b504dd/monitoring/api/v3/cloud-client/snippets.py#L116-L137) [doc](https://cloud.google.com/monitoring/custom-metrics/reading-metrics)
- [ ] [monitoring_read_timeseries_reduce](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/56a6b16fa1a8fa70df7b5018b12de815e1b504dd/monitoring/api/v3/cloud-client/snippets.py#L143-L167) [doc](https://cloud.google.com/monitoring/custom-metrics/reading-metrics)
- [ ] [monitoring_list_descriptors](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/56a6b16fa1a8fa70df7b5018b12de815e1b504dd/monitoring/api/v3/cloud-client/snippets.py#L173-L176) [doc](https://cloud.google.com/monitoring/custom-metrics/browsing-metrics)
- [ ] [monitoring_get_descriptor](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/56a6b16fa1a8fa70df7b5018b12de815e1b504dd/monitoring/api/v3/cloud-client/snippets.py#L202-L204) [doc](https://cloud.google.com/monitoring/custom-metrics/browsing-metrics)
- [ ] [monitoring_list_resources](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/56a6b16fa1a8fa70df7b5018b12de815e1b504dd/monitoring/api/v3/cloud-client/snippets.py#L182-L187) [doc](https://cloud.google.com/monitoring/custom-metrics/browsing-metrics)
- [ ] [monitoring_get_resource](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/56a6b16fa1a8fa70df7b5018b12de815e1b504dd/monitoring/api/v3/cloud-client/snippets.py#L193-L196) [doc](https://cloud.google.com/monitoring/custom-metrics/browsing-metrics)

**Comment by SurferJeffAtGoogle** [comment]
And these ones:

- [ ] [monitoring_alert_backup_policies](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/061b898007acc2be55b3f1e1bbdec470c4423b03/monitoring/api/v3/alerts-client/snippets.py#L94-L113) [doc](https://cloud.google.com/monitoring/alerts/using-alerting-api)
- [ ] [monitoring_alert_restore_policies](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/061b898007acc2be55b3f1e1bbdec470c4423b03/monitoring/api/v3/alerts-client/snippets.py#L118-L199) [doc](https://cloud.google.com/monitoring/alerts/using-alerting-api)
- [ ] [monitoring_alert_replace_channels](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/061b898007acc2be55b3f1e1bbdec470c4423b03/monitoring/api/v3/alerts-client/snippets.py#L75-L89) [doc](https://cloud.google.com/monitoring/alerts/using-alerting-api)
- [ ] [monitoring_alert_enable_policies](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/061b898007acc2be55b3f1e1bbdec470c4423b03/monitoring/api/v3/alerts-client/snippets.py#L47-L70) [doc](https://cloud.google.com/monitoring/alerts/using-alerting-api)
- [ ] [monitoring_alert_enable_channel](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/3c85b5a7b770e7c458b33570883604857f4db73c/monitoring/api/AlertSnippets/EnableNotificationChannel.cs#L16-L38)
- [ ] [monitoring_alert_list_channels](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/061b898007acc2be55b3f1e1bbdec470c4423b03/monitoring/api/v3/alerts-client/snippets.py#L37-L42) [doc](https://cloud.google.com/monitoring/alerts/using-channels-api)
- [ ] [monitoring_alert_delete_channel](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/3c85b5a7b770e7c458b33570883604857f4db73c/monitoring/api/AlertSnippets/DeleteNotificationChannel.cs#L16-L32)
- [ ] [monitoring_alert_create_channel](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/061b898007acc2be55b3f1e1bbdec470c4423b03/monitoring/api/v3/alerts-client/snippets.py#L120-L201) [doc](https://cloud.google.com/monitoring/alerts/using-channels-api)
- [ ] [monitoring_alert_list_policies](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/061b898007acc2be55b3f1e1bbdec470c4423b03/monitoring/api/v3/alerts-client/snippets.py#L27-L32) [doc](https://cloud.google.com/monitoring/alerts/using-alerting-api)
- [ ] [monitoring_alert_create_policy](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/061b898007acc2be55b3f1e1bbdec470c4423b03/monitoring/api/v3/alerts-client/snippets.py#L119-L200) [doc](https://cloud.google.com/monitoring/alerts/using-alerting-api)
- [ ] [monitoring_alert_update_channel](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/061b898007acc2be55b3f1e1bbdec470c4423b03/monitoring/api/v3/alerts-client/snippets.py#L121-L202) [doc](https://cloud.google.com/monitoring/alerts/using-channels-api)

**Comment by fhinkel** [comment]
Do we still need those samples? Or are they in a different repo?

**Comment by dazuma** [comment]
Monitoring samples are written and are in the google-cloud-ruby repo.
