### ISSUE TITLE
[Firestore] Improve "ruby-ness" of fs_return_info_transaction snippet

### ISSUE THREAD

**Issue by BenWhitehead** [GoogleCloudPlatform/ruby-docs-samples#446]

**Comment by BenWhitehead** [comment]
Came us as something we want to look at during review of https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/444

**Comment by quartzmo** [comment]
Closed by https://github.com/googleapis/google-cloud-ruby/pull/11147.
