### ISSUE TITLE
Ruby on Rails sample app for GAE Standard Ruby

### ISSUE THREAD

**Issue by toshimaru** [GoogleCloudPlatform/ruby-docs-samples#447]
Any plan to add Ruby on Rails sample app for GAE standard aside from sinatra Ruby app?

There are a lot of Rails users, so it should be useful.

**Comment by namusyaka** [comment]
Since I often heard from GCP developers in Japan that they want to see an example which runs Rails on AppEngine Standard, it's worth that providing the example.

If you're fine, I may be able to own this issue.

**Comment by NickNish09** [comment]
Is there any news on this one? I have a Rails project which I was trying to deploy to standard environment, but the connection with Redis is failing.

I tried the nodejs sample and it worked, with the same redis instance and same vpc-connector. Would be great if we had a similar docs as https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/memorystore/redis.

Anyway, thanks for the attention

**Comment by shivgautam** [comment]
I believe this was added a while ago. https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/main/appengine/rails-hello_world

If you need a bit larger app, please create a new issue. 

There are other sample Rails apps with CloudSQL DB connections for
 - postgresql: https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/main/appengine/rails-cloudsql-postgres
 - mysql: https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/main/appengine/rails-cloudsql-mysql
