### ISSUE TITLE
iot: Method name is incorrect in documentation

### ISSUE THREAD

**Issue by KidA001** [GoogleCloudPlatform/ruby-docs-samples#453]
The method call for sending a command to a device is wrong in your documentation: https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/iot/iot.rb#L654

Your documentation lists: `send_project_location_registry_group_device_command_to_device` but as of the `0.37.0` version of this gem, it's `send_project_location_registry_device_command_to_device`

**Comment by tbpg** [comment]
Thank you for letting us know! I'll work on a PR to fix it.

**Comment by tbpg** [comment]
Ah, no PR needed for this repo. I'll update the doc (https://cloud.google.com/iot/docs/how-tos/commands#iot-core-send-command-ruby).

**Comment by tbpg** [comment]
PR was, in fact, needed. :)

The doc should be updated and good to go.

Thanks, again, for letting us know! Feel free to file more issues if you spot any other problems.
