### ISSUE TITLE
Failing Build: Storage

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/ruby-docs-samples#455]
Falures due to:

```
Google::Cloud::PermissionDeniedError:
       quotaExceeded: Service account HMAC key limit reached
```

**Comment by quartzmo** [comment]
@frankyn Is there any chance that #445 is creating too many HMAC keys?

**Comment by frankyn** [comment]
+1, if the sample isn't cleaning up the hmac keys then yes. The limit is 5 right now.

**Comment by frankyn** [comment]
I think this was resolved by @jkwlui. I'm going to close it now.
