### ISSUE TITLE
Deprecated options used in "gcloud sql"

### ISSUE THREAD

**Issue by dacat** [GoogleCloudPlatform/ruby-docs-samples#458]
source: https://codelabs.developers.google.com/codelabs/cloud-app-engine-refinery-cms/index.html?index=..%2F..index#7

```

$ gcloud sql users set-password postgres no-host --instance=refinery-cloudsql-instance --password=some-password
ERROR: (gcloud.sql.users.set-password) Positional argument deprecated_host has been removed. Use --host instead.
Usage: gcloud sql users set-password USERNAME --instance=INSTANCE, -i INSTANCE [optional flags]
  optional flags may be  --async | --help | --host | --password |
                         --prompt-for-password
```

should be changed to 

 `gcloud sql users set-password postgres --instance=refinery-cloudsql-instance --password=some-password `

**Comment by TheRoyalTnetennba** [comment]
Thanks for reporting this. I've requested changes to the guide.

**Comment by TheRoyalTnetennba** [comment]
Opened a bug this guide. Closing as this repo contains none of the source for the codelab.
