### ISSUE TITLE
Wrong filter used when retrieving PROJECT_NUMBER

### ISSUE THREAD

**Issue by dacat** [GoogleCloudPlatform/ruby-docs-samples#459]
source: https://codelabs.developers.google.com/codelabs/cloud-app-engine-refinery-cms/index.html?index=..%2F..index#9

current: 
`gcloud projects list --filter "name:$GOOGLE_CLOUD_PROJECT"`

should be:
`gcloud projects list --filter "project_id:$GOOGLE_CLOUD_PROJECT"`

the environment variable $GOOGLE_CLOUD_PROJECT is set to $(gcloud config get-value project) earlier in the tutorial.

**Comment by TheRoyalTnetennba** [comment]
Thanks for reporting this. I've requested changes to the command

**Comment by TheRoyalTnetennba** [comment]
Opened a bug this guide. Closing as this repo contains none of the source for the codelab.
