### ISSUE TITLE
Create Cloud SQL connectivity sample for Postgres

### ISSUE THREAD

**Issue by kurtisvg** [GoogleCloudPlatform/ruby-docs-samples#471]
Create a copy of the [MySQL connectivity sample](https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/master/cloud-sql/mysql/activerecord) and update it to work with Postgres.

Requirements:

- PR the sample into this repo under `cloud_sql/postgres/activerecord`
- Update the following region tag(s): 
    * `cloud_sql_mysql_activerecord_connection` -> `cloud_sql_postgres_activerecord_connection`
    * `cloud_sql_mysql_activerecord_create` -> `cloud_sql_postgres_activerecord_create`
    * `cloud_sql_mysql_activerecord_limit` -> `cloud_sql_postgres_activerecord_limit`
    * `cloud_sql_mysql_activerecord_timeout` -> `cloud_sql_postgres_activerecord_timeout`
    * `cloud_sql_mysql_activerecord_backoff` -> `cloud_sql_postgres_activerecord_backoff`
- Update the README for Postgres and verify the instructions work

Please add myself as a reviewer.

Assigned: @quartzmo

FYI: @dmahugh, @jsimonweb

**Comment by crwilcox** [comment]
@kurtisvg is this all pretty interconnected work? Or could this be split at all?

**Comment by kurtisvg** [comment]
> @kurtisvg is this all pretty interconnected work? Or could this be split at all?

It's all interconnected. It is a single app that we use a couple specific parts as snippets. 

That said it's a fairly simple app and has a canonical already, so it just needs to be updated for a different database type.
