### ISSUE TITLE
Installing google-cloud-debugger 0.35.1 with native extensions Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by Sudarshan013** [GoogleCloudPlatform/ruby-docs-samples#482]
I am trying to install stackdriver gem in GCP Virtual Machine .
During "bundle install" I am getting the following error\
```

An error occurred while installing google-cloud-debugger (0.35.1), and
Bundler cannot continue.
Make sure that `gem install google-cloud-debugger -v '0.35.1'` succeeds before
bundling.


```
And when I install "google-cloud-debugger" , the following error gets generated 

`Installing google-cloud-debugger 0.35.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
`
How can I troubleshoot this issue

**Comment by dazuma** [comment]
* Which OS are you running? (For example, Alpine Linux is known to be tricky—you have to provide some extra parameters to get certain gems to compile.)
* Which ruby version are you running? (Ruby 2.7 is not known to be compatible yet.)
* Are you directly on a Compute Engine VM or in a container?
* Can you access the build logs? The error message should give you the path to the build log file, which should give you more information about what's going on.
