### ISSUE TITLE
Add guide for writing Ruby code sample applications and snippets

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/ruby-docs-samples#51]
**Story:** I'm a Rubyist that wants to contribute. 

**Issue:** 
1. Rubyist clicks on **CONTRIBUTING.md** at the bottom of the page https://github.com/GoogleCloudPlatform/ruby-docs-samples. 
2. Rubyist arrives at https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/CONTRIBUTING.md.
3. Rubyist clicks on **Google Cloud Platform Samples Style Guide** and arrives at https://github.com/GoogleCloudPlatform/Template/wiki/style.html. 
4. Rubyist unknowingly clicks on  **ruby-docs-samples** and goes back to https://github.com/GoogleCloudPlatform/ruby-docs-samples. 

**Possible Solution:** Insert the Ruby Style Guide

**Comment by remi** [comment]
As a contributor, I want to understand ...

 - How to add a new sample
 - How to modify an existing sample, eg. to provide a bug fix
