### ISSUE TITLE
Ruby Storage sample doesn't have a README

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/ruby-docs-samples#54]
**Story**
A Rubyist looks for a README.md to understand how [Storage](https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/master/storage) or [BigQuery](https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/master/bigquery) should be used similar to [Vision](https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/master/vision). 

**Issue** 
There is no README.md in the [Storage](https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/master/storage) sample and [BigQuery](https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/master/bigquery)

**Possible-Solution**
The Storage sample and BigQuery sample should have a README similar to [Vision](https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/master/vision).

**Comment by remi** [comment]
This fix will come with the new Storage sample ([branch](https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/new-storage-samples/storage))

Related (should fix this): #70
