### ISSUE TITLE
Question: onSnapShot firestore

### ISSUE THREAD

**Issue by rodgomesc** [GoogleCloudPlatform/ruby-docs-samples#631]
hello, there is any documentation about  how to monitoring real time changes in firestore collections using ruby? i don't see anything like onSnapshot

Thanks,

**Comment by quartzmo** [comment]
Hi @rodgomesc,

Thanks for this question. I think what you are looking for in the Ruby `google-cloud-firestore` client is the [`Query#listen`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-firestore/lib/google/cloud/firestore/query.rb#L932-L963) method, which is also aliased as `Query#on_snapshot`. The usage for other clients is explained in [Get realtime updates with Cloud Firestore](https://firebase.google.com/docs/firestore/query-data/listen), although for some reason the Ruby samples are not shown. You can find the source for the samples [here](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-firestore/samples/query_watch.rb#L134-L167), however. Hope this helps!
