### ISSUE TITLE
Pub/Sub: samples audit and cleanup

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/ruby-docs-samples#669]
In addition to #651 (ordering key), #628 (subscription detachment), #594 (DLQ), please also:  

Add:
- ~[ ] `pubsub_publisher_retry_settings` ([docs](https://cloud.google.com/pubsub/docs/publisher#retry))~
- [x] `pubsub_publish_with_error_handler` ([docs](https://cloud.google.com/pubsub/docs/publisher#publishing_messages)): instead of a simple publish example, this example should show how to handle publish failures. 
- [x] `pubsub_subscriber_sync_pull_with_lease` ([docs](https://cloud.google.com/pubsub/docs/pull#synchronous_pull_with_lease_management))

Remove:
- [x] Remove the region tag `pubsub_subscriber_sync_pull_custom_attributes` (but keep the region tag  `pubsub_subscriber_async_pull_custom_attributes`)

**Comment by quartzmo** [comment]
@anguillanneuf The `google-cloud-pubsub` veneer gem does not support custom retry settings at any scope (method, client, or global). However, it is easy to configure the global settings for an RPC via the underlying GAPIC library before constructing a client, as shown below. Do you think this is the right approach for the `pubsub_publisher_retry_settings` sample? I'm not aware of any sample for a veneer library that demonstrates configuration of a generated GAPIC client, so I thought I'd raise the question before adding the following sample to a PR:

```rb
def publisher_retry_settings topic_name:
  # [START pubsub_publisher_retry_settings]
  # topic_name = "Your Pubsub topic name"
  require "google/cloud/pubsub"

  # Configure global settings for an RPC in the underlying google-cloud-pubsub-v1 gem.
  Google::Cloud::PubSub::V1::Publisher::Client.configure do |config|
    config.rpcs.publish.timeout = 60.0
    config.rpcs.publish.retry_policy = {
      initial_delay: 0.1,
      max_delay:     60.0,
      multiplier:    1.3,
      retry_codes:   [
        "ABORTED",
        "CANCELLED",
        "INTERNAL",
        "RESOURCE_EXHAUSTED",
        "UNKNOWN",
        "UNAVAILABLE",
        "DEADLINE_EXCEEDED"
      ]
    }
  end

  pubsub = Google::Cloud::Pubsub.new

  topic = pubsub.topic topic_name
  topic.publish "This is a test message."

  puts "Message published."
  # [END pubsub_publisher_retry_settings]
end
```

**Comment by anguillanneuf** [comment]
@quartzmo Thanks for raising it. Yah, this looks incredibly similar to what we currently do in the Python sample, which isn't quite what we want to show. Let me remove this sample ask for Ruby until we have plans to add this at the client level. Feel free to add it to the backlog.
