### ISSUE TITLE
Add RuboCop with only some cops enabled

### ISSUE THREAD

**Issue by beccasaurus** [GoogleCloudPlatform/ruby-docs-samples#68]
The default RuboCop configuration does not match many of the styles used here in these samples.

The styles for code sample snippets varies greatly from that of production Ruby applications, eg. the goal of samples is clarity and we often do non-traditional things such as putting `require` statements into method definitions for the purpose of defining a snippet.

Add a RuboCop configuration and run via Travis that enforces some desired / common stylistic mistakes, eg. trailing whitespace or the use of the `and`, `or`, or `then` keywords

See also: [How to disable all cops except some](https://github.com/bbatsov/rubocop/issues/1918)

**Comment by quartzmo** [comment]
I'm going to try to add a Rubocop configuration this week.

**Comment by grant** [comment]
This issue is outdated. See #408.
