### ISSUE TITLE
All samples must have READMEs

### ISSUE THREAD

**Issue by beccca** [GoogleCloudPlatform/ruby-docs-samples#70]

**Comment by frankyn** [comment]
Notes for AppEngine Readme's
- Analytics

1. Setup analytics could have a link to: https://support.google.com/analytics/answer/1032385?hl=en 
2. README redirects a person to the parent appengine directory

- Static Page

1. Should link to https://cloud.google.com/appengine/docs/flexible/ruby/serving-static-files


- Sendgrid

1. State the version of the API we are using and link to the API docs for Sendgrid as well.
2. Maybe even directly linking to the gem: https://github.com/sendgrid/sendgrid-ruby

- CloudSQL

1. Describe what the sample is doing, similar to Cloud Datastore README. 

- Metadata

1. Describe what the sample is doing, (Displaying the IP address of the instance)

- Pubsub

1. Describe what the sample is doing. How it works and what's expected.

**Comment by broady** [comment]
Closing, please re-open (and re-assign) if still relevant.

If re-opening, probably best to change it to P2.
