### ISSUE TITLE
[Pub/Sub]: add sample for decoding and verifying JWT from Pub/Sub

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/ruby-docs-samples#719]
Please add a sample in [this](https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/master/appengine/pubsub) directory and show how to **decode** and **verify** a JWT included in the header of a Pub/Sub push message (when authenticated push is enabled). The other language (Go, Node.js, Java, Python) samples already [exist](https://cloud.google.com/pubsub/docs/push#authentication_and_authorization_by_the_push_endpoint).

I'm not sure if Ruby has a cloud client library for this task (please find out if you can), but it appears to have an API client library [`google-api-ruby-client`](https://github.com/googleapis/google-api-ruby-client) that does the job.

You can use Google's public keys referenced [here](https://developers.google.com/assistant/identity/google-sign-in#access_profile_information_in_your_backend) to verify JWTs from the real Pub/Sub service. For writing tests, use mocked public keys in other language samples.

You can use the region tag `gaeflex_net_pubsub_auth_push` for this sample.

**Comment by quartzmo** [comment]
@anguillanneuf Although I closed this issue when I merged #724, I was wondering if you want to consider changing the region tag `gaeflex_net_pubsub_auth_push` to something that emphasizes App Engine Standard (rather than Flex) as the default choice for Ruby users.

**Comment by anguillanneuf** [comment]
Thanks @quartzmo for flagging it! Let me get back to you after I have the region tag made.
