### ISSUE TITLE
Pub/Sub: distinguish between topic and subscription IDs and names

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/ruby-docs-samples#726]
Samples should refer to the fully qualified topic paths `projects/{}/topics/{}` as topic names and the actual string for the topic as the topic id. 

The same goes for subscriptions. 

For example, this should be `topic_id`. 
https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/b1a13ea51c868af607c4c88e768416f3ab47c615/pubsub/topics.rb#L17

**Comment by quartzmo** [comment]
There is a similar situation with `Subscription`. Should we also change `subscription_name` to `subscription_id` where the value is not the fully qualified subscription path?


https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/b1a13ea51c868af607c4c88e768416f3ab47c615/pubsub/subscriptions.rb#L17

**Comment by anguillanneuf** [comment]
Yes. 

Sorry I didn't look too carefully. By `subscription_name`, do you refer to the fully qualified subscription path? If that's the case, we don't have to change anything. 

I had thought that we were using `subscription_name` to refer to `subscription_id`.

**Comment by anguillanneuf** [comment]
Specifically in the README, 

> Example:
> `bundle exec ruby topics.rb create_topic my-new-topic`
> Topic `my-new-topic` created.

I would have thought that `my-new-topic` refers to a topic ID. If what's expected is a topic name, we can just update the README.

**Comment by quartzmo** [comment]
The design in google-cloud-pubsub is consistent, meaning that both `topic_name` and `subscription_name` parameters are **not** the fully qualified path.

See the API docs examples for [Topic#subscribe](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb#L374).

Also, if you look at the ruby-docs-samples test helper, you can see that the value is not fully qualified:

https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/b1a13ea51c868af607c4c88e768416f3ab47c615/pubsub/acceptance/helper.rb#L25-L27

**Comment by quartzmo** [comment]
We may also want to attempt to change these parameter names in google-cloud-pubsub. I haven't yet looked at how hard that will be to do.

**Comment by quartzmo** [comment]
It turns out that the `topic_name`, `subscription_name`, and `snapshot_name` parameters in the google-cloud-pubsub client support **both** the fully-qualified paths (names) and the shorter IDs:

https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb#L326-L339

@anguillanneuf Which should we show in these examples, the fully-qualified paths (names) or the shorter IDs?

**Comment by anguillanneuf** [comment]
Thanks for looking this up! 

Since both IDs and names are supported, the variables names used in the Ruby samples are not exactly wrong.  

But for consistency, let's go with the short IDs and name them as such (`.*_id`), like in the other examples (Java/Go/Python/C#/gcloud/REST). See: https://cloud.google.com/pubsub/docs/publisher#publishing_messages

It is easier to type a short ID than a full path and I'd imagine most people expect to supply a short ID when they run these samples.
