### ISSUE TITLE
Add basic Ruby on Rails sample

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/ruby-docs-samples#76]
Add simplest possible Ruby on Rails application that successfully deploys to the [Ruby runtime](https://cloud.google.com/appengine/docs/flexible/ruby/runtime) for [Google App Engine flexible environment](https://cloud.google.com/appengine/docs/flexible/ruby/)

This application will support documentation.

Application should include a few additions that demonstrate the App Engine flex runtime, eg.
- A static asset to serve to demonstrate that we default `config.public_file_server.enabled` to true via `RAILS_SERVE_STATIC_FILES`
- Production configuration of `secret_key_base` configuration, eg. via `SECRET_KEY_BASE` in app.yaml or some other means
- A working resourceful controller, eg. generated via `rails scaffold post title body:text` using Cloud SQL (extremely common Rails use-case :: database configuration can be replaced with any SQL database that the the user desires)

The README for this application should include all of the commands taken to create this application, beginning with `rails new`.  Most of this information will be provided via documentation, which should be linked to from the README, but this application README should demonstrate the _very few_ commands necessary to `gcloud app deploy` an application generated via `rails new` on the latest verion of Ruby on Rails

Tests should verify CRUD actions work on the deployed application

Possible directory location: `rails/getting_started` or `ruby_on_rails/getting_started`.  When developers find this repository, I'd like "Ruby on Rails" to be immediately noticeable in the directories and READMEs.  The `ruby_on_rails` directory should have a README directing users to our Rails documentation and Google App Engine flexible environment documentation for Ruby

**Comment by frankyn** [comment]
Obsolete
