### ISSUE TITLE
Refactor spec helper methods into a shared folder

### ISSUE THREAD

**Issue by beccasaurus** [GoogleCloudPlatform/ruby-docs-samples#83]

**Comment by grant** [comment]
Which specific methods are we talking about?
Doesn't it make sense to keep most methods in their own folder?

**Comment by grant** [comment]
I've looked at [all `spec_helper.rb` files in this repo](https://github.com/GoogleCloudPlatform/ruby-docs-samples/search?q=spec_helper.rb&unscoped_q=spec_helper.rb) and determined that the cost of creating a shared folder outweighs the benefits.

Unless there is more duplicative boilerplate code, it's probably best to separate the helper methods.
