### ISSUE TITLE
Rails on App Engine ruby install and docker build exceeding 10 Minutes

### ISSUE THREAD

**Issue by thinkocapo** [GoogleCloudPlatform/ruby-docs-samples#935]
Hello, I followed these instructions https://cloud.google.com/ruby/rails/appengine

- I ran` bundle exec rails server` and did not add any additional Gems
- I did not change ruby version in .ruby-version file, 2.7.5
- I'm using the same app.yaml recommended in the docs
- I ran the app locally first on my machine and confirmed it worked.

### Problem
I run `gcloud app deploy` and here is the end of the output, see full-output.txt for full log:

...the ruby install that takes +7 minutes
```
Step #1: [91mDownloading ruby-2.7.5.tar.bz2...
Step #1: [0m[91m-> https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.5.tar.bz2
Step #1: [0m[91mInstalling ruby-2.7.5...
Step #1: [0m[91mInstalled ruby-2.7.5 to /opt/rbenv/versions/2.7.5
```
...followed by an error eventually:
```
Step #1: Fetching mini_mime 1.1.2
Step #1: Installing mini_mime 1.1.2
Step #1: Fetching activestorage 7.0.2.2
Step #1: Installing activestorage 7.0.2.2
Step #1: Fetching mail 2.7.1
Step #1: Installing mail 2.7.1


Step #1: Fetching digest 3.1.0
Step #1: Installing digest 3.1.0 with native extensions
-----------------------------------------------------------------------------------------------

ERROR: (gcloud.app.deploy) Cloud build failed. Check logs at https://console.cloud.google.com/cloud-build/builds/<MY_BUILD_ID>?project=<MY_PROJECT_ID> Failure status: UNKNOWN: Error Response: [4] DEADLINE_EXCEEDED
```
[full-output.txt](https://github.com/GoogleCloudPlatform/ruby-docs-samples/files/8121045/full-output.txt)

### Expected Outcome
Not get a DEADLINE_EXCEEDED error.

### Questions
I did some research on this DEADLINE_EXCEEDED error... Is there a 10 Minute deadline for building?

It's interesting that the ruby install finishes in 9-10 minutes, and then the DEADLINE_EXCEEDED happens in the next steps (as it reaches 10 minutes).

Is there a way to speed up the download and/or install of ruby?

Is it normal to take this long?

I've deployed App Engine node, python and spring services and never ran into a build timeout like this.

**Comment by NivedhaSenthil** [comment]
Sorry for getting back late, I am able to successfully deploy and did not face any deadline exceeded issue. Are you still facing this ? yes it does take time to build but should not fail like above.

**Comment by NivedhaSenthil** [comment]
Closing this issue for now, please feel free to reopen if the issue still exists.
